# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
import baml_py

from . import stream_types, types, type_builder
from .parser import LlmResponseParser, LlmStreamParser
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME as __runtime__


class BamlAsyncClient:
    __options: DoNotUseDirectlyCallManager
    __stream_client: "BamlStreamClient"
    __http_request: "BamlHttpRequestClient"
    __http_stream_request: "BamlHttpStreamRequestClient"
    __llm_response_parser: LlmResponseParser
    __llm_stream_parser: LlmStreamParser

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options
        self.__stream_client = BamlStreamClient(options)
        self.__http_request = BamlHttpRequestClient(options)
        self.__http_stream_request = BamlHttpStreamRequestClient(options)
        self.__llm_response_parser = LlmResponseParser(options)
        self.__llm_stream_parser = LlmStreamParser(options)

    def with_options(self,
        tb: typing.Optional[type_builder.TypeBuilder] = None,
        client_registry: typing.Optional[baml_py.baml_py.ClientRegistry] = None,
        collector: typing.Optional[typing.Union[baml_py.baml_py.Collector, typing.List[baml_py.baml_py.Collector]]] = None,
        env: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None,
        tags: typing.Optional[typing.Dict[str, str]] = None,
        on_tick: typing.Optional[typing.Callable[[str, baml_py.baml_py.FunctionLog], None]] = None,
    ) -> "BamlAsyncClient":
        options: BamlCallOptions = {}
        if tb is not None:
            options["tb"] = tb
        if client_registry is not None:
            options["client_registry"] = client_registry
        if collector is not None:
            options["collector"] = collector
        if env is not None:
            options["env"] = env
        if tags is not None:
            options["tags"] = tags
        if on_tick is not None:
            options["on_tick"] = on_tick
        return BamlAsyncClient(self.__options.merge_options(options))

    @property
    def stream(self):
      return self.__stream_client

    @property
    def request(self):
      return self.__http_request

    @property
    def stream_request(self):
      return self.__http_stream_request

    @property
    def parse(self):
      return self.__llm_response_parser

    @property
    def parse_stream(self):
      return self.__llm_stream_parser

    async def ChatAgent(self, messages: typing.List["types.Message"],
        baml_options: BamlCallOptions = {},
    ) -> str:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.ChatAgent(messages=messages,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="ChatAgent", args={
                "messages": messages,
            })
            return typing.cast(str, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def CodeActAgent(self, messages: typing.List["types.Message"],code: typing.Optional[str] = None,code_result: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> types.CodeActAgentDecision:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.CodeActAgent(messages=messages,code=code,code_result=code_result,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="CodeActAgent", args={
                "messages": messages,"code": code,"code_result": code_result,
            })
            return typing.cast(types.CodeActAgentDecision, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def CodeLocator(self, messages: typing.List["types.Message"],
        baml_options: BamlCallOptions = {},
    ) -> types.LocatorDecision:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.CodeLocator(messages=messages,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="CodeLocator", args={
                "messages": messages,
            })
            return typing.cast(types.LocatorDecision, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def DecideAction(self, messages: typing.List["types.Message"],tool: typing.Optional["types.ToolCall"] = None,
        baml_options: BamlCallOptions = {},
    ) -> types.ActionDecision:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.DecideAction(messages=messages,tool=tool,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="DecideAction", args={
                "messages": messages,"tool": tool,
            })
            return typing.cast(types.ActionDecision, __result__.cast_to(types, types, stream_types, False, __runtime__))
    


class BamlStreamClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ChatAgent(self, messages: typing.List["types.Message"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[str, str]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="ChatAgent", args={
            "messages": messages,
        })
        return baml_py.BamlStream[str, str](
          __result__,
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def CodeActAgent(self, messages: typing.List["types.Message"],code: typing.Optional[str] = None,code_result: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.CodeActAgentDecision, types.CodeActAgentDecision]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="CodeActAgent", args={
            "messages": messages,"code": code,"code_result": code_result,
        })
        return baml_py.BamlStream[stream_types.CodeActAgentDecision, types.CodeActAgentDecision](
          __result__,
          lambda x: typing.cast(stream_types.CodeActAgentDecision, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.CodeActAgentDecision, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def CodeLocator(self, messages: typing.List["types.Message"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.LocatorDecision, types.LocatorDecision]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="CodeLocator", args={
            "messages": messages,
        })
        return baml_py.BamlStream[stream_types.LocatorDecision, types.LocatorDecision](
          __result__,
          lambda x: typing.cast(stream_types.LocatorDecision, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.LocatorDecision, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def DecideAction(self, messages: typing.List["types.Message"],tool: typing.Optional["types.ToolCall"] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.ActionDecision, types.ActionDecision]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="DecideAction", args={
            "messages": messages,"tool": tool,
        })
        return baml_py.BamlStream[stream_types.ActionDecision, types.ActionDecision](
          __result__,
          lambda x: typing.cast(stream_types.ActionDecision, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.ActionDecision, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    

class BamlHttpRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    async def ChatAgent(self, messages: typing.List["types.Message"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ChatAgent", args={
            "messages": messages,
        }, mode="request")
        return __result__
    async def CodeActAgent(self, messages: typing.List["types.Message"],code: typing.Optional[str] = None,code_result: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="CodeActAgent", args={
            "messages": messages,"code": code,"code_result": code_result,
        }, mode="request")
        return __result__
    async def CodeLocator(self, messages: typing.List["types.Message"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="CodeLocator", args={
            "messages": messages,
        }, mode="request")
        return __result__
    async def DecideAction(self, messages: typing.List["types.Message"],tool: typing.Optional["types.ToolCall"] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="DecideAction", args={
            "messages": messages,"tool": tool,
        }, mode="request")
        return __result__
    

class BamlHttpStreamRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    async def ChatAgent(self, messages: typing.List["types.Message"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ChatAgent", args={
            "messages": messages,
        }, mode="stream")
        return __result__
    async def CodeActAgent(self, messages: typing.List["types.Message"],code: typing.Optional[str] = None,code_result: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="CodeActAgent", args={
            "messages": messages,"code": code,"code_result": code_result,
        }, mode="stream")
        return __result__
    async def CodeLocator(self, messages: typing.List["types.Message"],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="CodeLocator", args={
            "messages": messages,
        }, mode="stream")
        return __result__
    async def DecideAction(self, messages: typing.List["types.Message"],tool: typing.Optional["types.ToolCall"] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="DecideAction", args={
            "messages": messages,"tool": tool,
        }, mode="stream")
        return __result__
    

b = BamlAsyncClient(DoNotUseDirectlyCallManager({}))