# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions

import baml_py

from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ChatAgent(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> str:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ChatAgent", llm_response=llm_response, mode="request")
        return typing.cast(str, __result__)

    def CodeActAgent(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.CodeActAgentDecision:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="CodeActAgent", llm_response=llm_response, mode="request")
        return typing.cast(types.CodeActAgentDecision, __result__)

    def CodeLocator(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.LocatorDecision:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="CodeLocator", llm_response=llm_response, mode="request")
        return typing.cast(types.LocatorDecision, __result__)

    def DecideAction(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ActionDecision:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="DecideAction", llm_response=llm_response, mode="request")
        return typing.cast(types.ActionDecision, __result__)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ChatAgent(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> str:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ChatAgent", llm_response=llm_response, mode="stream")
        return typing.cast(str, __result__)

    def CodeActAgent(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.CodeActAgentDecision:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="CodeActAgent", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.CodeActAgentDecision, __result__)

    def CodeLocator(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.LocatorDecision:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="CodeLocator", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.LocatorDecision, __result__)

    def DecideAction(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ActionDecision:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="DecideAction", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ActionDecision, __result__)

    