# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (10)
# #########################################################################

class ActionDecision(BaseModel):
    message: typing.Optional["Message"] = None
    tools: typing.List[typing.Union["AddTool", "SubtractTool"]]

class AddTool(BaseModel):
    name: typing.Optional[typing_extensions.Literal['add']] = None
    a: typing.Optional[int] = None
    b: typing.Optional[int] = None

class CodeActAgentDecision(BaseModel):
    message: typing.Optional["Message"] = None
    code: typing.Optional[str] = None

class GlobTool(BaseModel):
    name: typing.Optional[typing_extensions.Literal['glob_file_search']] = None
    glob_pattern: typing.Optional[str] = None
    target_directory: typing.Optional[str] = None

class GrepTool(BaseModel):
    name: typing.Optional[typing_extensions.Literal['grep']] = None
    pattern: typing.Optional[str] = None
    path: typing.Optional[str] = None
    type: typing.Optional[str] = None

class ListDirTool(BaseModel):
    name: typing.Optional[typing_extensions.Literal['list_dir']] = None
    target_directory: typing.Optional[str] = None

class LocatorDecision(BaseModel):
    explanation: typing.Optional[str] = None
    tool: typing.Optional[typing.Union["GrepTool", "GlobTool", "ListDirTool"]] = None
    findings: typing.Optional[str] = None

class Message(BaseModel):
    role: typing.Optional[typing.Union[typing_extensions.Literal['user'], typing_extensions.Literal['assistant'], typing_extensions.Literal['system']]] = None
    content: typing.Optional[str] = None

class SubtractTool(BaseModel):
    name: typing.Optional[typing_extensions.Literal['subtract']] = None
    a: typing.Optional[int] = None
    b: typing.Optional[int] = None

class ToolCall(BaseModel):
    name: typing.Optional[str] = None
    args: typing.Optional[str] = None
    result: typing.Optional[str] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
