# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (0)
# #########################################################################

# #########################################################################
# Generated classes (10)
# #########################################################################

class ActionDecision(BaseModel):
    message: typing.Optional["Message"] = None
    tools: typing.List[typing.Union["AddTool", "SubtractTool"]]

class AddTool(BaseModel):
    name: typing_extensions.Literal['add']
    a: int
    b: int

class CodeActAgentDecision(BaseModel):
    message: typing.Optional["Message"] = None
    code: typing.Optional[str] = None

class GlobTool(BaseModel):
    name: typing_extensions.Literal['glob_file_search']
    glob_pattern: str
    target_directory: typing.Optional[str] = None

class GrepTool(BaseModel):
    name: typing_extensions.Literal['grep']
    pattern: str
    path: typing.Optional[str] = None
    type: typing.Optional[str] = None

class ListDirTool(BaseModel):
    name: typing_extensions.Literal['list_dir']
    target_directory: typing.Optional[str] = None

class LocatorDecision(BaseModel):
    explanation: typing.Optional[str] = None
    tool: typing.Optional[typing.Union["GrepTool", "GlobTool", "ListDirTool"]] = None
    findings: typing.Optional[str] = None

class Message(BaseModel):
    role: typing.Union[typing_extensions.Literal['user'], typing_extensions.Literal['assistant'], typing_extensions.Literal['system']]
    content: str

class SubtractTool(BaseModel):
    name: typing_extensions.Literal['subtract']
    a: int
    b: int

class ToolCall(BaseModel):
    name: str
    args: str
    result: str

# #########################################################################
# Generated type aliases (0)
# #########################################################################
