# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.ActionDecision": types.ActionDecision,
    "stream_types.ActionDecision": stream_types.ActionDecision,

    "types.AddTool": types.AddTool,
    "stream_types.AddTool": stream_types.AddTool,

    "types.CodeActAgentDecision": types.CodeActAgentDecision,
    "stream_types.CodeActAgentDecision": stream_types.CodeActAgentDecision,

    "types.GlobTool": types.GlobTool,
    "stream_types.GlobTool": stream_types.GlobTool,

    "types.GrepTool": types.GrepTool,
    "stream_types.GrepTool": stream_types.GrepTool,

    "types.ListDirTool": types.ListDirTool,
    "stream_types.ListDirTool": stream_types.ListDirTool,

    "types.LocatorDecision": types.LocatorDecision,
    "stream_types.LocatorDecision": stream_types.LocatorDecision,

    "types.Message": types.Message,
    "stream_types.Message": stream_types.Message,

    "types.SubtractTool": types.SubtractTool,
    "stream_types.SubtractTool": stream_types.SubtractTool,

    "types.ToolCall": types.ToolCall,
    "stream_types.ToolCall": stream_types.ToolCall,


}